
services:
  jenkins:
    image: jenkins/jenkins:2.498-jdk17
    ports:
      - 8080:8080
      - 50000:50000
    cpu_count: 2
    mem_limit: 2g
    restart: no

  nexus:
    image: sonatype/nexus3:3.70.4
    ports:
      - 8081:8081
    cpu_count: 2
    mem_limit: 1g
    restart: no
